name: Davincibox
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      davincibox_flavor: davincibox
