name: Davincibox
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build_base:
    name: Build davincibox
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      davincibox_flavor: davincibox
  build_opencl:
    name: Build davincibox-opencl
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      davincibox_flavor: davincibox-opencl
